### ISSUE TITLE
PA Review: Teams

### ISSUE THREAD

**Issue by addriv** [addriv/Hakuna#18]

**Comment by niartenyaw** [comment]
This looks awesome!
Some changes:
+ Clicking outside the dropdown should close it
+ When in `Create a Workspace` or `Remove from workspace`, the menu should be behind the modal transparency
+ In the upper right drop down, hovering over projects doesn't color the entire bar.

**Comment by addriv** [comment]
Ok @niartenyaw I made the changes you requested.

**Comment by niartenyaw** [comment]
Awesome, looks good!
