### ISSUE TITLE
PA Review: Projects

### ISSUE THREAD

**Issue by addriv** [addriv/Hakuna#24]

**Comment by addriv** [comment]
@niartenyaw I've finished new, update, and delete project functionality. Let me know if I need to make any changes!

**Comment by niartenyaw** [comment]
Looks awesome! Some comments:

+ The `Delete Project` and `Update Project` buttons could use some vertical padding
+ Give the text inside the inputs some padding on the left


+ Something I just noticed about another portion, the `hover` over projects in the upper right dropdown isn't aligned with the border lines between them

**Comment by addriv** [comment]
@niartenyaw ready for another review!

**Comment by niartenyaw** [comment]
Awesome, looks great!!
