### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by addriv** [addriv/Hakuna#8]

**Comment by niartenyaw** [comment]
Functionality is great, it could still use some more styling. I think everything needs some more room/padding around it on the login/signup page. 
+ `EMAIL` and `PASSWORD` are too close to their inputs
+ Add hover effects for buttons, including the `cursor` to be a `pointer`
+ more padding around text of the buttons
+ `Log In` header seems a bit out of place
+ Add padding above `Don't have an account?` section 
+ Have the entire SessionForm more vertically centered
+ Maybe move `Demo` button next to the other

**Comment by niartenyaw** [comment]
@addriv Not sure you saw this, I'll make sure to tag you in future comments.

**Comment by addriv** [comment]
@niartenyaw Hey Aaron. I think I got everything. Can you review when you get the chance? I noticed the app doesn't seem to work when I'm on mobile. Is this normal for Heroku?

**Comment by niartenyaw** [comment]
@addriv awesome, looks great! The dashboard is looking really good too. Hmm you should be able to load it on mobile (may take a bit if you aren't using binary canary and haven't visited it in a bit) but the styling may be way off. There's additional css steps you would need to take to make it responsive to mobile screen sizes. Don't worry about it for now though, that's something you can do as a bonus feature or after full stacks.
